### ISSUE TITLE
Issues Building the Utility

### ISSUE THREAD

**Issue by ghost** [wortiz/msh2exo#1]
Hi Wortiz, 

Forgive me because this is probably a very basic question. I do not understand how to build this utility based on the building instructions. I'm a complete novice when it comes to this. 

I would really love to use this utility because I need something similar at the moment. Is there any way we could get in contact and you could give me a few more step-by-step type of instructions on how to get this thing going? I appreciate your consideration. 

How difficult would it be to add compatibility for 8 noded elements (second-order incomplete elements in gmsh)?

Thank you for the consideration.

**Comment by wortiz** [comment]
Hi,

What are you having trouble with?

The only requirement is a built SEACASExodus which can be followed from the SEACAS repository linked in the README.

I think SEACAS requires a UNIX-like system so Linux / Windows WSL with Ubuntu / (Maybe Msys2 on windows) / or Mac OS

For Linux I think installing these prerequesites in the common distros would allow you to build SEACAS using the repositories instructions. I'm not as familiar with Mac OS or MSYS2

```
For Ubuntu

sudo apt-get install wget git build-essential m4 zlib1g-dev libx11-dev gfortran

For CentOS / Fedora

sudo [yum|dnf] install git patch gcc gcc-c++ gcc-gfortran m4 make wget bzip2 tar zlib-devel libX11-devel
``` 

Alternatively you can build SEACAS using spack, I know that works on both WSL and Ubuntu or Fedora.

Then following this should just work: https://github.com/wortiz/msh2exo#building

---

I added QUAD8 and it seems to work with the following mesh:

https://github.com/wortiz/msh2exo-examples/tree/master/2d/quad8

**Comment by ghost** [comment]
I use windows which is probably why a lot of this doesn't make sense to me. Hypothetically speaking, assuming that I have the SEACAS repository installed on my windows computer, is it possible (and how difficult would it be) to build this for Windows? If so, does msh2exo also require the Windows WSL? Again, I appreciate you taking the time to answer my very basic questions.

**Comment by wortiz** [comment]
> I use windows which is probably why a lot of this doesn't make sense to me. Hypothetically speaking, assuming that I have the SEACAS repository installed on my windows computer, is it possible (and how difficult would it be) to build this for Windows? 

I've added some notes here: https://github.com/wortiz/msh2exo/#windows-build-notes

Initial tests seem to be working, the msh files have to be in DOS format which gmsh will do if ran on windows

This assumes you have a working Visual Studio, I think any of the recent ones should support C++14 and if you can build SEACAS ExodusII library you should be able to build `msh2exo`

> If so, does msh2exo also require the Windows WSL?

WSL is a bit easier to get SEACAS built, and if you build SEACAS there you would also need to build `msh2exo` there. You have access to your mounted drives through WSL so it isn't that hard to use it through that if that is the way you go.

WSL does require the msh files be in unix format so you would have to install dos2unix and run that before converting msh files created on Windows if you go that route.

**Comment by ghost** [comment]
Thank you so much for the time you've spent on this. I am starting to see the light at the end of the tunnel here!

One question about the vcpkg install for netcdf. I don't see that as an available package on the vcpkg website (https://vcpkg.io/en/packages.html). I see "netcdf-c" and "netcdf-cxx4". Similarly, in the C:\src\vcpkg\ports folder, I only see these two packages (netcdf-c and netcdf-cxx4). Am I missing something here? 

Otherwise, I've went through the majority of the build process and I seem to be getting somewhere. I installed the "netcdf-c" package during the building process, but at the end (when attempting to use "msh2exo.exe") it ended up telling me the following message (obviously because I didn't install netcdf, I installed netcdf-c): 

![image](https://user-images.githubusercontent.com/107716549/181404831-d6e057bf-fc8e-45e6-b222-d984d1097622.png)

**Comment by wortiz** [comment]
> One question about the vcpkg install for netcdf. I don't see that as an available package on the vcpkg website (https://vcpkg.io/en/packages.html). I see "netcdf-c" and "netcdf-cxx4". Similarly, in the C:\src\vcpkg\ports folder, I only see these two packages (netcdf-c and netcdf-cxx4). Am I missing something here?

Thanks, I've updated the notes it should be `netcdf-c`

> Otherwise, I've went through the majority of the build process and I seem to be getting somewhere. I installed the "netcdf-c" package during the building process, but at the end (when attempting to use "msh2exo.exe") it ended up telling me the following message (obviously because I didn't install netcdf, I installed netcdf-c):

I think this is my failing with CMake and Windows. I'm not to sure how to install the DLL's with the executable, I've made a note in the README but you should copy the DLL's in the ~~installed bin folder (or wherever you want to use it).~~ build folder, following instructions that would be build/Release and they should be copied to install/bin and the DLLs I have are:

   ```
   hdf5.dll
   hdf5_hl.dll
   libcurl.dll
   netcdf.dll
   zlib1.dll
   ```

Just a note this is a command line utility which I think are a bit more rare on Windows so usage is through the terminal, for example the following might be a possible command in PowerShell to change input.msh to output.exoII

```
C:\src\msh2exo\install\bin\msh2exo.exe input.msh output.exoII
```

**Comment by ghost** [comment]
I do believe I have msh2exo installed with the dll files in the build folder now. I can run msh2exo --help and it looks like it works properly (as shown).

![image](https://user-images.githubusercontent.com/107716549/181414841-6887f7f7-f6d0-4eea-a6b1-cf1b5bdca2a5.png)

I downloaded your example mesh "multibox_quad8.msh" and am trying to convert it. When I type the command, nothing happens. I'm not sure where (if anywhere) an output file is going. It should just be in the folder I'm running it from, correct? I placed the test mesh in the folder with msh2exo.exe and I'm attempting to run from there. Any guidance here?

![image](https://user-images.githubusercontent.com/107716549/181415192-47be17c4-7951-45e5-adc4-0ab450486217.png)

**Comment by wortiz** [comment]
Here are the files in for a Windows machine, I'll try to include both windows and linux examples at some point in the other repository.

[multibox_quad8_windows_example.zip](https://github.com/wortiz/msh2exo/files/9205216/multibox_quad8_windows_example.zip)


The way the gmsh reader is written it needs the files to be created by a Windows gmsh to read properly. The ones in the examples were for linux 

I also don't have enough error checking so thats why its not showing anything. 

If you run with verbose mode (-v) it should show the following for the attached zip file:

```
C:\src\msh2exo\build\Release\msh2exo.exe -v .\multibox_quad8.msh .\multibox_quad8.e
.\multibox_quad8.e: Generating node_elem_map
.\multibox_quad8.e: Generating side set pairs
.\multibox_quad8.e: Searching boundary 0 for sides, 1 nodes
.\multibox_quad8.e: Searching boundary 1 for sides, 1 nodes
.\multibox_quad8.e: Searching boundary 2 for sides, 17 nodes
.\multibox_quad8.e: Searching boundary 3 for sides, 17 nodes
.\multibox_quad8.e: Searching boundary 4 for sides, 17 nodes
.\multibox_quad8.e: Searching boundary 5 for sides, 17 nodes
.\multibox_quad8.e: Searching boundary 6 for sides, 17 nodes
.\multibox_quad8.e: Initializing exodus
.\multibox_quad8.e: inserting connectivity
         BLOCK "lower_domain" (id 1): type QUAD8, n_elements 32, n_nodes_per_elem 8
         BLOCK "upper_domain" (id 2): type QUAD8, n_elements 32, n_nodes_per_elem 8
.\multibox_quad8.e: inserting coords
.\multibox_quad8.e: inserting nodesets
         NS "top_left" (id 6): 1 nodes
         NS "middle_right" (id 7): 1 nodes
         NS "bottom" (id 1): 17 nodes
         NS "right" (id 2): 17 nodes
         NS "top" (id 3): 17 nodes
         NS "left" (id 4): 17 nodes
         NS "interface" (id 5): 17 nodes
.\multibox_quad8.e: inserting sidesets
         SS "bottom" (id 1): 8 sides
         SS "right" (id 2): 8 sides
         SS "top" (id 3): 8 sides
         SS "left" (id 4): 8 sides
         SS "interface" (id 5): 16 sides
```

**Comment by ghost** [comment]
When you export a mesh from gmsh using the .msh extension, what format and options do you choose. Your file that you just sent did work for me  but the meshes I'm exporting from gmsh are not working. 

Here are the options I see when I try to export a mesh:
Format -- 
Save all elements -- 
Save parametric coordinates --

EDIT - I think I needed to use the SDK version of GMSH to export the mesh. I was able to convert the mesh created from the SDK GMSH software. I should have read the build instructions more carefully! You're the man!

I'm going to do some more testing tomorrow with my own mesh files.

**Comment by bradyrespec** [comment]
Oh, I think I just have the normal "gmsh-4.10.5-Windows64" vs the "gmsh-4.10.5-Windows64-sdk". I'm guessing I'll have to figure out how to use the SDK?

**Comment by wortiz** [comment]
Glad you seem to have something working.

I'm able to use the non-SDK version, but just make sure your meshes have Physical Groups as it uses this to create the exodus data, see here: https://github.com/wortiz/msh2exo#conversion-from-physical-groups-to-exodusii-data

I am able to use non-SDK version for the above windows geo file by clicking 2D in Gmsh and then Save to save the msh file.  This can also be accomplished with -2 on the command line

The SDK support mentioned in the README is to use gmsh itself to read the msh files but I haven't tested this on Windows yet. and requires specifying the Gmsh_DIR in the cmake configure for msh2exo

**Comment by ghost** [comment]
Can you give me more information on what exactly is required for a exodus block to be created in 2D? Are the physical points doing anything for the block creation in your multibox example (if so, what?).  I don't think I'm defining the physical groups correctly. 

Based on the examples, it looks like there needs to be physical curves surrounding the block, then a physical surface that resides within those physical curves. I'm not sure what the points are doing. For reference, this is a simplified version of what I'm trying to create (the real mesh could be 20-30 material blocks) :

Element blocks that represent materials (can be made up of one or more surfaces which can be grouped together in a physical surface)
Side sets and node sets that represent the boundaries of the model (can be made up of one or more curves, grouped within a physical curve, that represent a boundary of the mesh.. left, right, bottom, top, etc).

![image](https://user-images.githubusercontent.com/107716549/181592899-78c7ccbd-49e2-42a8-8898-c5c26d27317f.png)

Does it just create nodesets and sidesets for every physical curve in the model? At least for my application, it makes sense for physical surfaces to be converted directly to element blocks and physical curves to be converted to side sets and node sets. I'm sure for other applications it would get more complicated.

**Comment by wortiz** [comment]
>  Are the physical points doing anything for the block creation in your multibox example (if so, what?).

No they should just be making single node nodesets

>Based on the examples, it looks like there needs to be physical curves surrounding the block, then a physical surface that resides within those physical curves. I'm not sure what the points are doing. For reference, this is a simplified version of what I'm trying to create (the real mesh could be 20-30 material blocks) :

There shouldn't be a need for curves to surround a block, I was just testing an internal sideset

> Does it just create nodesets and sidesets for every physical curve in the model? At least for my application, it makes sense for physical surfaces to be converted directly to element blocks and physical curves to be converted to side sets and node sets. I'm sure for other applications it would get more complicated.

For 2D meshes each physical surface should be turned into a block and each physical curve should be turned into a nodeset/sideset, and each physical point to a single noded nodeset

So for your example I would make physical curves first in the order you want (I think you can specify the number as well to be sure)

Then I would make physical surfaces for each block in the order you want them to be numbered.

You shouldn't need physical points or curves if you don't want nodesets or sidesets for those curves the only required part should be physical surfaces for 2D

**Comment by ghost** [comment]
I've been able to create meshes that are compatible with msh2exo using .geo files. My intention is to use Python to generate the mesh and for some reason I'm having problems with the way it is outputting the files. I'm trying to use the same commands (generally) and it isn't recognizing something correctly. I'm sure it's just a setting or something I don't have set correctly in the Python API. I don't think it is an issue with msh2exo.. I just don't have the right output settings or something for python gmsh. 

I don't really expect your help here, but if your curious, here is an example of code I'm having problem with. 

## --- 

`import gmsh
import sys


gmsh.initialize()

gmsh.model.add("test")

gmsh.model.occ.addRectangle(0, 0, 0, 1, 0.5, tag=1)

gmsh.model.occ.synchronize()

gmsh.model.addPhysicalGroup(2, [1])

gmsh.model.mesh.generate(2)

gmsh.option.setNumber("Mesh.Algorithm", 8)
gmsh.option.setNumber("Mesh.RecombinationAlgorithm", 2)
gmsh.option.setNumber("Mesh.SecondOrderIncomplete", 1)
gmsh.option.setNumber("Mesh.RecombineAll", 1)
gmsh.option.setNumber("Mesh.Smoothing", 2)
gmsh.option.setNumber("Mesh.SaveAll", 1)
gmsh.model.mesh.setOrder(2)
gmsh.write("WortizCode_Python.msh")

gmsh.finalize()`



EDIT: Figured out why it wasn't working, at least for this example. I had to set a name for the surface for it to recognize it.

Replaced "gmsh.model.occ.addRectangle(0, 0, 0, 1, 0.5, tag=1)" with "gmsh.model.addPhysicalGroup(2, [1], tag=1, name='test')"

**Comment by ghost** [comment]
I'm now able to create blocks with msh2exo when only one surface is grouped into the physical surface (i.e., surface 1 goes into physical group 1), but I'm having trouble if more than one geometrical surface is grouped into a physical surface (i.e., surfaces 1 and 2 grouped into physical surface 1).  

Do you also have this problem and is there any way to make it work?

**Comment by wortiz** [comment]
> EDIT: Figured out why it wasn't working, at least for this example. I had to set a name for the surface for it to recognize it.

Thanks for that, good to know.

Until I can address error messages, make sure that there is a `$PhysicalNames` section in the mesh file.

> Do you also have this problem and is there any way to make it work?

I checked and there was a bug causing this, it should be fixed with the latest, thanks

The following now works for me for a single block spanning multiple physical groups

```
//+
SetFactory("OpenCASCADE");
Rectangle(1) = {0, 0, 0, 1, 0.5, 0};
//+
Rectangle(2) = {0, 0.5, 0, 1, 0.5, 0};
//+
Physical Curve("bottom") = {1};
//+
Physical Curve("right") = {2, 5};
//+
Physical Curve("top") = {6};
//+
Physical Curve("left") = {9, 4};
//+
Physical Curve("interface") = {3};
//+
Physical Point("top_left") = {6};
//+
Physical Point("middle_right") = {3};
//+
Physical Surface("domain") = {1,2};
//+

Coherence;

Mesh.Algorithm = 8;

Mesh.RecombinationAlgorithm = 2;

Mesh.ElementOrder = 2;

Mesh.SecondOrderIncomplete = 1;

Mesh.RecombineAll = 1;

Coherence Mesh;

Mesh.Smoothing = 2;
```

**Comment by wortiz** [comment]
I'm going to close this since you have the utility built and to avoid a catch-all issue. 

Feel free to open new issues for new bugs, or if my fix didn't work for the multiple physical groups in one block.
